#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import json
from pathlib import Path
import logging
from playwright.sync_api import sync_playwright
from . import config as fb_config

def convert_cookies_to_netscape(cookies):
    """Chuyển đổi định dạng cookie của Playwright sang Netscape mà yt-dlp có thể đọc."""
    header = """# Netscape HTTP Cookie File
# https://curl.haxx.se/docs/http-cookies.html
# This file was generated by the script.
#
"""
    netscape_cookies = []
    for cookie in cookies:
        # Netscape format: domain, include_subdomains, path, secure, expiration, name, value
        domain = cookie['domain']
        include_subdomains = str(domain.startswith('.')).upper()
        path = cookie['path']
        secure = str(cookie['secure']).upper()
        # Chuyển đổi expiration từ epoch seconds sang integer
        expires = str(int(cookie['expires'])) if cookie['expires'] != -1 else '0'
        name = cookie['name']
        value = cookie['value']
        netscape_cookies.append(
            f"{domain}\t{include_subdomains}\t{path}\t{secure}\t{expires}\t{name}\t{value}\n"
        )
    return header + "".join(netscape_cookies)

def main():
    """Mở trình duyệt để người dùng đăng nhập và lưu lại cookie."""
    with sync_playwright() as p:
        print("🚀 Mở trình duyệt để đăng nhập Facebook và tạo profile...")
        print(f"ℹ️  Dữ liệu profile sẽ được lưu tại: {fb_config.PROFILE_DIR.resolve()}")
        fb_config.PROFILE_DIR.mkdir(exist_ok=True)

        context = p.chromium.launch_persistent_context(
            fb_config.PROFILE_DIR,
            headless=False,
            args=["--disable-blink-features=AutomationControlled"]
        )
        page = context.new_page()
        page.goto("https://www.facebook.com")
        
        print("\n" + "="*50)
        print("👉 Vui lòng đăng nhập vào tài khoản Facebook của bạn trên trình duyệt.")
        print("✨ Script sẽ tự động tiếp tục sau khi phát hiện bạn đã đăng nhập thành công.")
        print("="*50)

        try:
            # Chờ sự xuất hiện của một phần tử chỉ có sau khi đăng nhập (ví dụ: khu vực news feed chính)
            # Timeout được đặt là 5 phút (300000 ms) để người dùng có đủ thời gian
            logged_in_element_selector = 'div[role="main"]'
            print("⏳ Đang chờ tín hiệu đăng nhập thành công...")
            page.wait_for_selector(logged_in_element_selector, timeout=300000)

            print("\n✅ Đăng nhập thành công được phát hiện!")
            print("🔄 Đang lấy và lưu cookie...")
            cookies = context.cookies()
            netscape_format_cookies = convert_cookies_to_netscape(cookies)
            fb_config.COOKIE_FILE.write_text(netscape_format_cookies)

            print(f"✅ Đã lưu cookie thành công vào: {fb_config.COOKIE_FILE}")
            print(f"✅ Đã lưu profile trình duyệt vào: {fb_config.PROFILE_DIR.resolve()}")

        except Exception as e:
            print("\n❌ Không phát hiện được đăng nhập trong vòng 5 phút hoặc có lỗi xảy ra.")
            logging.debug(f"Lỗi khi chờ đăng nhập: {e}")

        context.close()

if __name__ == "__main__":
    main()